operations:
  workerProcess:
    - type: action
      impl: dx-asset-compute-worker-1/worker
hooks:
  post-app-run: adobe-asset-compute devtool
  test: adobe-asset-compute test-worker
actions: actions
runtimeManifest:
  packages:
    dx-asset-compute-worker-1:
      license: Apache-2.0
      actions:
        worker:
          function: actions/worker/index.js
          web: 'yes'
          runtime: 'nodejs:16'
          limits:
            concurrency: 10
          annotations:
            require-adobe-auth: true
        worker-1:
          function: actions/worker-1/index.js
          web: 'yes'
          runtime: 'nodejs:16'
          limits:
            concurrency: 10
          annotations:
            require-adobe-auth: true
